### PR TITLE
lib: Simplify error handling slightly

### PR DESCRIPTION
**Pull request by woodruffw**
As mentioned in https://github.com/luser/spawn-ptrace/pull/2#discussion_r505879852 :slightly_smiling_face:

### CODE REVIEW

**Comment by luser** [comment]
Thanks!

**Comment by woodruffw** [comment]
Thanks for the merge! Are there any other blockers on a new release?

**Comment by luser** [comment]
Nope! I cleaned up that test that checked the example in the README that I commented on, and made the description in the README / crate-level docs slightly nicer while I was at it, and I've just released 0.1.2:
https://crates.io/crates/spawn-ptrace/0.1.2

Let me know if you encounter any other issues! Thanks again!

**Comment by woodruffw** [comment]
Awesome, thanks a ton! I'll let you know (and will keep contributing where possible 🙂 ).

**Pull request merged**
